### ISSUE TITLE
Also remove lock xml files

### ISSUE THREAD

**Issue by ToLive** [AndroPlus-org/magisk-module-oplus-cn2global#2]
Hi! Based on this article https://androplus.org/en/entry/oplus-region-lock-china-hardware/ can you, please, also add backup and removing of lock xml files?

    my_bigball/etc/regionlock_config.xml
    my_product/etc/regionlock_config.xml
    my_region/etc/regionlock_config.xml

**Comment by AndroPlus-org** [comment]
OK, added in v03.

**Comment by ToLive** [comment]
Thank you! But sad, this is not working( I mean this doesn't lift the lock.

**Comment by AndroPlus-org** [comment]
Please try to delete the data of "com.android.phone", maybe it contains old locked state data.
