### ISSUE TITLE
Region lock disabling feature

### ISSUE THREAD

**Issue by Rancor0** [AndroPlus-org/magisk-module-oplus-cn2global#3]
Hello, this is regarding the region lock disabling feature. 
The thing is, your module DOES work for disabling region lock, not only for Realme but for Oneplus 11 too. But it works in a strange way: if you install the module AFTER your OP11 gets region locked (unable to make calls), then region lock gets removed and you can make calls just fine. It does nothing if you install it before that. After the module disables region lock, you still get daily warning pop-ups about blocking, and after 3-4 days your phone will get region locked again, BUT if you delete and reinstall the module, it will remove region lock yet again.
So, you have to reinstall the module every now and then for working calls, which is kinda tedious, but it works. Can you look into the region locking issue a bit further? There should be a way to make it stop completely, I hope so.

**Comment by AndroPlus-org** [comment]
Great to hear unlocking works!
I'm in a region not covered by region lock, so debugging is difficult...
Does rebooting after being region locked have no effect?
The module applies props while booting so theoretically, it will be unlocked upon reboot without deleting/reinstalling.

**Comment by Rancor0** [comment]
Honestly that might be the case, since every time I got locked I deleted the module in magisk, reinstalled it and then rebooted. But I'll have to wait a few days to get another lock to fully confirm it. My phone is currently not locked (I reinstalled the module yesterday), so I tried to lock it by spamming reboot (people on xda/4pda said that rebooting ~10 times causes the phone to get locked), but was unable to, even though those annoying pop-ups about region customization appeared every single time.

**Comment by AndroPlus-org** [comment]
OK, then maybe setting these props removes the lock (temporary).
```
setprop persist.sys.oplus.radio.globalregionlock 0,0
setprop persist.sys.oplus.radio.haslimited false
setprop ro.oplus.radio.checkservice false
setprop persist.sys.oplus.bnoticetimes 0
setprop persist.sys.oplus.pnoticetimes 0
setprop gsm.sim.oplus.radio.fnoticetime 0
```
Those props are set by /system_ext/frameworks/oplus-telephony-common.jar so creating Xposed module to hook it should remove region lock completely, but I'm not good at making Xposed module and couldn't hook jar files...

For the meantime, I changed noticetimes props to -200000 in this test version.
If the system just read the props and plus 1, it will be -199999 or something (you can check it by `getprop persist.sys.oplus.pnoticetimes` in adb shell) and it won't trigger region lock for a while.
[magisk-module-oplus-cn2global.zip](https://github.com/AndroPlus-org/magisk-module-oplus-cn2global/files/11723239/magisk-module-oplus-cn2global.zip)

**Comment by tr1ckert** [comment]
Just wanted to comment you are lifesaver, the message still comes up but no more region lock after 10 reboots.

**Comment by fatalcoder524** [comment]
Can't you set 
`
setprop persist.sys.oplus.radio.globalregionlock 0,0
setprop persist.sys.oplus.radio.haslimited false
setprop ro.oplus.radio.checkservice false
setprop persist.sys.oplus.bnoticetimes 0
setprop persist.sys.oplus.pnoticetimes 0
setprop gsm.sim.oplus.radio.fnoticetime 0
`

These in post-fs-data ? It's currently in service.sh!

**Comment by AndroPlus-org** [comment]
@fatalcoder524
OK, changed in v09
https://github.com/AndroPlus-org/magisk-module-oplus-cn2global/releases/tag/v09

**Comment by fatalcoder524** [comment]
Hi, post-fs-data is a blocking mode script during boot script. Please don't run root. Just set it once and then move the loop to service.sh if you want periodic loops.

**Comment by fatalcoder524** [comment]
Also don't use setprop in post-fs-data. Taken from Magisk developer guides:

**post-fs-data mode**

- This stage is BLOCKING. The boot process is paused before execution is done, or 10 seconds have passed.
- Scripts run before any modules are mounted. This allows a module developer to dynamically adjust their modules before it gets mounted.
- This stage happens before Zygote is started, which pretty much means everything in Android

**WARNING: using setprop will deadlock the boot process! Please use resetprop -n <prop_name> <prop_value> instead.**
